### ISSUE TITLE
the diskCategory is not supported; diskCategory is cloud

### ISSUE THREAD

**Issue by carlossg** [AliyunContainerService/alicloud-storage-provisioner#3]
Reading the docs looks like the only volume type able to do <10Gi is `basic`, so I try to use the `alicloud-disk-common` storage class in a PVC like this

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alicloud-disk-common
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-common
  resources:
    requests:
      storage: 5Gi
```

But I get this error

```
kube-system/alicloud-disk-controller-557cdf7fb8-7c5zt[alicloud-disk-controller]: I0516 06:12:36.120303       1 controller.go:1167] scheduleOperation[provision-jx/alicloud-disk-common[6e1e35b4-77a1-11e9-a0c2-06e1af112585]]
kube-system/alicloud-disk-controller-557cdf7fb8-7c5zt[alicloud-disk-controller]: E0516 06:12:38.358441       1 controller.go:895] Failed to provision volume for claim "jx/alicloud-disk-common" with StorageClass "alicloud-disk-common": Aliyun API Error: RequestId: 60C267C3-0B37-4C16-B670-7682AA907644 Status Code: 403 Code: InvalidDataDiskCategory.NotSupported Message: the diskCategory is not supported; diskCategory is cloud
```

From the web ui I don't see basic disks, only ultra and ssd, so I don't know if they are no longer available
